## To modify by developer(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'arduino_ubuntu'

package-url = 'https://github.com/quantumm/pymodaq_plugins_arduino_ubuntu'
description = 'A plugin to read an analog output from an Arduino board on Ubuntu'

author = 'David Bresteau'
author-email = 'david.bresteau@cea.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.3.6', 'pyfirmata2']

[features]  # defines the plugin features contained into this plugin
instruments = true  # true if plugin contains instrument classes (else false, notice the lowercase for toml files)
extensions = false  # true if plugins contains dashboard extensions
models = false  # true if plugins contains pid models or other models (optimisation...)
h5exporters = false  # true if plugin contains custom h5 file exporters
scanners = false  # true if plugin contains custom scan layout (daq_scan extensions)

